"""Plan execution engine for autonomous agent.

This module executes the plans generated by the planner, invoking the appropriate
data source modules and handling errors gracefully.
"""

from typing import Dict, Any, List
from datetime import datetime

from .state import State, AgentAction
from .modules import invoke_module, MODULE_REGISTRY
from ..utils.logger import get_logger

logger = get_logger(__name__)


def execute_plan(state: State) -> State:
    """
    Execute the current plan in the state.
    
    Args:
        state: Current workflow state with plan to execute
    
    Returns:
        Updated state with plan execution results
    """
    plan = state.get("plan")
    if not plan or not plan.get("steps"):
        logger.warning("no_plan_to_execute", req_id=state.get("req_id"))
        return state
    
    context = state["context"]
    req_id = state.get("req_id", "unknown")
    
    logger.info(
        "executing_plan",
        req_id=req_id,
        steps_count=len(plan["steps"]),
        iteration=context["iteration_count"]
    )
    
    executed_steps = 0
    failed_steps = 0
    
    for i, step in enumerate(plan["steps"]):
        action = step.get("action")
        params = step.get("params", {})
        
        # Strict validation before execution
        if action not in MODULE_REGISTRY:
            failed_steps += 1
            error_msg = f"Unknown action '{action}' not in registry"
            logger.error("step_validation_failed", req_id=req_id, step_index=i, error=error_msg)
            continue
        
        if params is None:
            failed_steps += 1
            error_msg = f"Action '{action}' has null params (use empty object {{}})"
            logger.error("step_validation_failed", req_id=req_id, step_index=i, error=error_msg)
            continue
        
        logger.debug(
            "executing_step",
            req_id=req_id,
            step_index=i,
            action=action,
            params_keys=list(params.keys()) if isinstance(params, dict) else "invalid_params"
        )
        
        try:
            # Add user_id to params if not present (common requirement)
            if "client_id" not in params and action == "fetch_customer":
                params["client_id"] = state.get("user_id")
            
            # Execute the module and track state changes
            original_keys = set(context["data_sources"].keys())
            context = invoke_module(action, context, params)
            new_keys = set(context["data_sources"].keys())
            added_keys = list(new_keys - original_keys)
            
            # Map specific actions to expected state keys
            expected_keys = {
                "fetch_customer": ["customer"],
                "fetch_market": ["market_data"],
                "rag_search": ["rag"],
                "compute_decision": ["decision"]
            }
            
            expected = expected_keys.get(action, [])
            actual_added = [k for k in expected if k in context["data_sources"] and context["data_sources"][k] is not None]
            
            executed_steps += 1
            
            logger.debug(
                "step_executed_successfully",
                req_id=req_id,
                step_index=i,
                action=action,
                state_keys_added=actual_added,
                expected_keys=expected
            )
            
        except Exception as e:
            failed_steps += 1
            error_msg = str(e)
            
            logger.error(
                "step_execution_failed",
                req_id=req_id,
                step_index=i,
                action=action,
                error=error_msg
            )
            
            # Log failed action to context history
            failed_action = AgentAction(
                action=action,
                params=params,
                success=False,
                error=error_msg,
                timestamp=datetime.utcnow().isoformat() + "Z"
            )
            context["history"].append(failed_action)
            
            # Apply error handling strategies
            _handle_step_failure(action, error_msg, context, state)
    
    # Update state with modified context
    state["context"] = context
    
    logger.info(
        "plan_execution_completed",
        req_id=req_id,
        executed_steps=executed_steps,
        failed_steps=failed_steps,
        total_steps=len(plan["steps"])
    )
    
    return state


def _handle_step_failure(action: str, error: str, context: Dict[str, Any], state: State):
    """
    Handle specific step failures with recovery strategies.
    
    Args:
        action: The action that failed
        error: Error message
        context: Current agent context
        state: Current workflow state
    """
    req_id = state.get("req_id", "unknown")
    
    if action == "fetch_market":
        # Market data failure - check if it's due to staleness
        if "stale" in error.lower():
            logger.info("market_stale_fallback", req_id=req_id)
            # Use cached data anyway but mark as stale
            context["data_sources"]["market_data"] = {
                "stale": True,
                "error": "Using stale cached data",
                "condition": "unknown"
            }
        else:
            logger.warning("market_fetch_failed_completely", req_id=req_id, error=error)
            context["data_sources"]["market_data"] = {"error": error}
    
    elif action == "rag_search":
        # RAG search failure - provide fallback policy summary
        if "no results" in error.lower() or "empty" in error.lower():
            logger.info("rag_no_results_fallback", req_id=req_id)
            context["data_sources"]["rag"] = {
                "snippets": [],
                "fallback_summary": "No specific policy found; using general lending guidelines",
                "error": "No relevant policy documents found"
            }
        else:
            logger.warning("rag_search_failed_completely", req_id=req_id, error=error)
            context["data_sources"]["rag"] = {
                "error": error,
                "fallback_summary": "Policy search unavailable; applying conservative criteria"
            }
    
    elif action == "fetch_customer":
        # Customer data failure is critical - can't proceed without it
        logger.error("customer_fetch_critical_failure", req_id=req_id, error=error)
        context["data_sources"]["customer"] = {"error": error}
        # Reduce confidence significantly
        context["confidence"] = 0.1
    
    elif action == "compute_decision":
        # Decision computation failure - try with available data or conservative fallback
        logger.warning("decision_computation_failed", req_id=req_id, error=error)
        if context["data_sources"].get("customer"):
            # Try conservative decision based on risk grade only
            customer_data = context["data_sources"]["customer"]
            risk_grade = customer_data.get("risk_grade", "C")
            
            if risk_grade == "A":
                fallback_decision = "DECLINE"
                fallback_score = 0.2
                fallback_reasons = ["High risk grade", "Conservative assessment due to system error"]
            elif risk_grade == "D":
                fallback_decision = "COUNTER"  # Conservative even for low risk
                fallback_score = 0.5
                fallback_reasons = ["Conservative assessment due to system error"]
            else:
                fallback_decision = "DECLINE"
                fallback_score = 0.3
                fallback_reasons = ["Conservative assessment due to system error"]
            
            context["data_sources"]["decision"] = {
                "decision": fallback_decision,
                "score": fallback_score,
                "reasons": fallback_reasons,
                "method": "conservative_fallback",
                "error": error
            }
            
            logger.info(
                "conservative_decision_fallback",
                req_id=req_id,
                decision=fallback_decision,
                risk_grade=risk_grade
            )
        else:
            context["data_sources"]["decision"] = {"error": error}


def validate_execution_readiness(state: State) -> bool:
    """
    Validate that the state is ready for plan execution.
    
    Args:
        state: Current workflow state
    
    Returns:
        True if ready for execution, False otherwise
    """
    plan = state.get("plan")
    context = state.get("context")
    
    if not plan:
        logger.warning("no_plan_for_execution", req_id=state.get("req_id"))
        return False
    
    if not plan.get("steps"):
        logger.warning("plan_has_no_steps", req_id=state.get("req_id"))
        return False
    
    if not context:
        logger.error("no_context_for_execution", req_id=state.get("req_id"))
        return False
    
    # Check for infinite loop prevention
    if context.get("iteration_count", 0) > 10:
        logger.error("too_many_iterations", req_id=state.get("req_id"))
        return False
    
    return True


def get_execution_summary(state: State) -> Dict[str, Any]:
    """
    Get a summary of the execution results.
    
    Args:
        state: Current workflow state after execution
    
    Returns:
        Execution summary dict
    """
    context = state.get("context", {})
    history = context.get("history", [])
    
    # Count successes and failures
    total_actions = len(history)
    successful_actions = sum(1 for action in history if action.get("success", False))
    failed_actions = total_actions - successful_actions
    
    # Get data availability
    data_sources = context.get("data_sources", {})
    available_sources = []
    error_sources = []
    
    for source, data in data_sources.items():
        if data is None:
            continue
        elif isinstance(data, dict) and "error" in data:
            error_sources.append(source)
        elif isinstance(data, list) and len(data) == 0:
            continue
        else:
            available_sources.append(source)
    
    # Determine readiness for decision
    has_customer = "customer" in available_sources
    has_decision = "decision" in available_sources
    ready_for_decision = has_customer and (has_decision or context.get("iteration_count", 0) >= 3)
    
    return {
        "total_actions": total_actions,
        "successful_actions": successful_actions,
        "failed_actions": failed_actions,
        "available_data_sources": available_sources,
        "error_data_sources": error_sources,
        "confidence": context.get("confidence", 0.0),
        "iteration_count": context.get("iteration_count", 0),
        "ready_for_decision": ready_for_decision,
        "has_customer_data": has_customer,
        "has_computed_decision": has_decision
    }


def should_retry_execution(state: State, execution_summary: Dict[str, Any]) -> bool:
    """
    Determine if execution should be retried with a new plan.
    
    Args:
        state: Current workflow state
        execution_summary: Summary from get_execution_summary
    
    Returns:
        True if should retry, False if should finalize
    """
    # Don't retry if we have a decision
    if execution_summary["has_computed_decision"]:
        return False
    
    # Don't retry if too many iterations
    if execution_summary["iteration_count"] >= 5:
        logger.warning("max_iterations_reached_no_retry", req_id=state.get("req_id"))
        return False
    
    # Retry if we don't have customer data and haven't failed too many times
    if not execution_summary["has_customer_data"] and execution_summary["failed_actions"] < 3:
        return True
    
    # Retry if we have customer data but no decision and some actions succeeded
    if (execution_summary["has_customer_data"] and 
        not execution_summary["has_computed_decision"] and 
        execution_summary["successful_actions"] > 0):
        return True
    
    # Don't retry if most actions failed
    if execution_summary["failed_actions"] > execution_summary["successful_actions"]:
        return False
    
    return False


def create_emergency_fallback_decision(state: State) -> State:
    """
    Create an emergency fallback decision when all else fails.
    
    Args:
        state: Current workflow state
    
    Returns:
        State with emergency decision populated
    """
    req_id = state.get("req_id", "unknown")
    context = state.get("context", {})
    
    logger.warning("creating_emergency_fallback_decision", req_id=req_id)
    
    # Try to use any available customer data
    customer_data = context.get("data_sources", {}).get("customer")
    if customer_data and isinstance(customer_data, dict) and "error" not in customer_data:
        risk_grade = customer_data.get("risk_grade", "C")
        
        # Very conservative decision based on risk grade only
        if risk_grade in ["A", "B"]:
            decision = "DECLINE"
            score = 0.1
            reasons = ["Conservative assessment due to system limitations"]
        else:
            decision = "COUNTER"
            score = 0.3
            reasons = ["Limited data available", "Conservative assessment"]
    else:
        # No customer data - decline
        decision = "DECLINE"
        score = 0.0
        reasons = ["Unable to retrieve customer data", "System error"]
    
    # Populate state fields
    state["decision"] = decision
    state["score"] = score
    state["reason_codes"] = reasons
    state["final_answer"] = f"Decision: {decision}. Due to system limitations, a conservative assessment was applied. Please contact support for manual review."
    
    # Update context
    if "data_sources" not in context:
        context["data_sources"] = {}
    
    context["data_sources"]["decision"] = {
        "decision": decision,
        "score": score,
        "reasons": reasons,
        "method": "emergency_fallback",
        "computed_at": datetime.utcnow().isoformat() + "Z"
    }
    
    state["context"] = context
    
    logger.info(
        "emergency_fallback_decision_created",
        req_id=req_id,
        decision=decision,
        score=score
    )
    
    return state
