"""State definition for the loan approval LangGraph workflow."""

import uuid
import os
from typing import TypedDict, Literal, Optional, List, Dict, Any

from ..utils.logger import get_logger

logger = get_logger(__name__)


class Message(TypedDict, total=False):
    """Chat message for conversation memory."""
    role: str  # "user" | "assistant" | "system"
    content: str
    ts: Optional[str]


class AgentAction(TypedDict):
    """Represents a single action in the agent's plan."""
    action: str
    params: Dict[str, Any]
    success: Optional[bool]
    error: Optional[str]
    timestamp: Optional[str]


class Context(TypedDict, total=False):
    """Agent's internal belief state and context."""
    query: str
    risk_tier: Optional[str]  # e.g., 'high', 'medium', 'low'
    data_sources: Dict[str, Any]  # e.g., {"customer": {...}, "market": {...}, "rag": [...]}
    history: List[AgentAction]  # Past actions with outcomes
    confidence: Optional[float]  # Agent's confidence in current data/decision
    iteration_count: int  # Number of planning iterations


class PlanStep(TypedDict):
    """A single step in an agent plan."""
    action: Literal["fetch_customer", "fetch_market", "rag_search", "compute_decision"]
    params: Dict[str, Any]  # non-optional, can be empty {}, but never None


class AgentPlan(TypedDict):
    """Plan generated by the LLM planner."""
    reasoning: str
    steps: List[PlanStep]  # len >= 1
    final_decision: Optional[Literal["APPROVE", "COUNTER", "DECLINE", "INFORM"]]
    confidence: float  # 0.0 <= confidence <= 1.0


class State(TypedDict, total=False):
    """State schema for the loan approval workflow."""
    
    # Request context
    req_id: str
    user_id: int
    question: str
    
    # Conversation memory (bounded rolling window)
    memory: List[Message]  # optional, default window size from env MEMORY_WINDOW=6
    
    # Agent-specific fields
    context: Context
    plan: Optional[AgentPlan]
    autonomous_mode: bool  # Flag to enable autonomous vs rule-based behavior
    
    # Data inputs (legacy - may be moved to context.data_sources)
    client: Optional[Dict[str, Any]]
    market_data: Optional[Dict[str, Any]]
    market_stale: bool
    
    # Decision outputs
    decision: Optional[Literal["APPROVE", "COUNTER", "DECLINE", "INFORM"]]
    reason_codes: List[str]
    score: Optional[float]
    
    # RAG & explanation
    policy_snippets: List[Dict[str, Any]]
    final_answer: Optional[str]
    explanation: Optional[str]  # Processed explanation text
    snippets: List[str]  # Legacy snippets list for backward compatibility
    references: List[Dict[str, Any]]  # Enhanced reference metadata
    
    # Dialogue Manager fields for enhanced customer service
    quick_replies: List[Dict[str, str]]  # Quick reply buttons for UI
    cta: Optional[Dict[str, str]]  # Call-to-action button
    product_context: Optional[str]  # Detected product context


def new_state(req_id: str, user_id: int, question: str, autonomous: bool = False, memory: List[Message] = None) -> State:
    """
    Create a new state instance for the workflow.
    
    Args:
        req_id: Request ID for tracking
        user_id: Authenticated user ID
        question: User's loan question
        autonomous: Whether to use autonomous mode (default: False for backward compatibility)
        memory: Optional conversation memory list
    
    Returns:
        Initialized state dict
    """
    # Get memory window size from environment, default to 6
    memory_window = int(os.getenv('MEMORY_WINDOW', '6'))
    
    # Initialize context for autonomous mode
    context = Context(
        query=question,
        risk_tier=None,
        data_sources={
            "customer": None,
            "market_data": None,
            "rag": []
        },
        history=[],
        confidence=None,
        iteration_count=0
    )
    
    state = State(
        req_id=req_id,
        user_id=user_id,
        question=question,
        context=context,
        plan=None,
        autonomous_mode=autonomous,
        memory=memory or [],  # Initialize empty memory list if none provided
        client=None,
        market_data=None,
        market_stale=False,
        decision=None,
        reason_codes=[],
        score=None,
        policy_snippets=[],
        final_answer=None
    )
    
    logger.info(
        "state_initialized",
        req_id=req_id,
        user_id=user_id,
        question_length=len(question),
        autonomous_mode=autonomous
    )
    
    return state


def generate_request_id() -> str:
    """Generate a unique request ID."""
    return f"REQ-{uuid.uuid4().hex[:12].upper()}"


def sanitize_state_for_logging(state: State) -> Dict[str, Any]:
    """
    Sanitize state for safe logging (remove sensitive data).
    
    Args:
        state: Workflow state
    
    Returns:
        Sanitized state dict
    """
    sanitized = {}
    
    # Safe fields to log
    safe_fields = [
        "req_id", "user_id", "decision", "reason_codes", 
        "score", "market_stale", "final_answer"
    ]
    
    for field in safe_fields:
        if field in state:
            sanitized[field] = state[field]
    
    # Sanitize client data (keep only non-sensitive aggregates)
    if state.get("client"):
        client = state["client"]
        sanitized["client"] = {
            "client_id": client.get("client_id"),
            "risk_grade": client.get("risk_grade"),
            "education_level": client.get("education_level"),
            "family_size": client.get("family_size"),
            "has_annual_income": bool(client.get("annual_income")),
            "has_risk_grade": bool(client.get("risk_grade"))
        }
    
    # Sanitize market data (remove detailed components)
    if state.get("market_data"):
        market = state["market_data"]
        sanitized["market_data"] = {
            "has_cbj_rate": "cbj_rate" in market,
            "has_cpi_yoy": "cpi_yoy" in market,
            "has_re_index": "re_price_index" in market,
            "market_risk_score": market.get("market_risk_score", {}).get("value"),
            "metric_count": len(market)
        }
    
    # Policy snippets (keep metadata, truncate text)
    if state.get("policy_snippets"):
        sanitized["policy_snippets"] = [
            {
                "section_id": snippet.get("section_id"),
                "page_start": snippet.get("page_start"),
                "score": snippet.get("score"),
                "text_length": len(snippet.get("text", ""))
            }
            for snippet in state["policy_snippets"][:3]  # Only first 3 for logging
        ]
    
    # Question (truncate if long)
    if state.get("question"):
        question = state["question"]
        sanitized["question"] = question[:100] + "..." if len(question) > 100 else question
    
    # Final answer (truncate if long)
    if state.get("final_answer"):
        answer = state["final_answer"]
        sanitized["final_answer_length"] = len(answer)
        sanitized["final_answer_preview"] = answer[:50] + "..." if len(answer) > 50 else answer
    
    return sanitized


def validate_state(state: State) -> bool:
    """
    Validate state has required fields.
    
    Args:
        state: Workflow state to validate
    
    Returns:
        True if state is valid
    """
    required_fields = ["req_id", "user_id", "question"]
    
    for field in required_fields:
        if field not in state or state[field] is None:
            logger.error("state_validation_failed", missing_field=field)
            return False
    
    return True


def get_state_summary(state: State) -> Dict[str, Any]:
    """
    Get a summary of the current state for status reporting.
    
    Args:
        state: Workflow state
    
    Returns:
        State summary dict
    """
    return {
        "req_id": state.get("req_id"),
        "user_id": state.get("user_id"),
        "has_client": bool(state.get("client")),
        "has_market": bool(state.get("market_data")),
        "market_stale": state.get("market_stale", False),
        "decision": state.get("decision"),
        "score": state.get("score"),
        "reason_count": len(state.get("reason_codes", [])),
        "policy_snippets_count": len(state.get("policy_snippets", [])),
        "has_final_answer": bool(state.get("final_answer")),
        "completed": bool(state.get("final_answer"))
    }
